### ISSUE TITLE
Enterprise/Org Level billing metrics

### ISSUE THREAD

**Issue by pdreker** [promhippie/github_exporter#10]
Scrape and output Billing Statistics for GH Enterprises and Organizations. Specifically:
* /orgs/{org}/settings/billing/actions
* /orgs/{org}/settings/billing/packages
* /orgs/{org}/settings/billing/shared-storage

All metrics include "total", "total paid" (basically "in excess of inluded amount") and "included amount".

Same metrics are available on the Enterpise Level:
* /enterprises/{enterprise}/settings/billing/actions
* /enterprises/{enterprise}/settings/billing/packages
* /enterprises/{enterprise}/settings/billing/shared-storage

Interestingly enough only the shared storage metric delivers a "days left in cycle" to see, where in the billing cycle we currently are.

These metrics would allow for proactive monitoring and extrapolation of used resources to enable an early warning system to trigger before actions just stop working.

**Comment by tboerger** [comment]
Looks like google/go-github doesn't provide methods for these API endpoints, but with [NewRequest](https://github.com/google/go-github/blob/v32.1.0/github/github.go#L342) it should be possible to gather this information. You are using GitHub Enterprise?

**Comment by pdreker** [comment]
Yes, using an enterprise subscription. I can test.

**Comment by tboerger** [comment]
After merging #13 it would be great if you should test the `:latest` Docker image or the pre-built binaries to make sure it's working correctly on your GitHub Enterprise.

**Comment by mafrosis** [comment]
Happy to confirm that this is working for me on a private GHE instance
