### ISSUE TITLE
Feat: Increase `perPage` setting

### ISSUE THREAD

**Issue by norman-zon** [promhippie/github_exporter#187]
We have about 700 repos in our Organisation, which leads to hitting the API rate-limit, even when using App-Auth, when scraping them all with `GITHUB_EXPORTER_REPOS: <org>/*`.
Is there a specific reason you set [perPage](https://github.com/promhippie/github_exporter/blob/b4214a1c0774925ad5aa519ac0aa5234baad61fc/pkg/exporter/helper.go#L23) to 50 instead of a higher value, so that there are less separate API calls?

Thanks again for your support!

**Comment by tboerger** [comment]
I can't remember the initial reason for this page size, for the runner and workflow collectors I have set the value to 200 and totally forgot the other pager. I think I will add a config flag for that and default to a value like 200. Need to check the maximum allowed value.

**Comment by tboerger** [comment]
The new version v2.1.0 is incoming :)
