### ISSUE TITLE
Failed to fetch repos: context deadline exceeded

### ISSUE THREAD

**Issue by dhawalseth** [promhippie/github_exporter#218]
After using 2.2.1 version, I get past the nil pointer error #217, but still run into:

│ level=error ts=2023-06-09T21:49:05.77855249Z collector=repo msg="Failed to fetch repos" name=org_name/* err="context deadline exceeded"             │

We do have a lot of repos under this org (16K+)

It works when provide the exact repo name.

**Comment by tboerger** [comment]
Wow, that's quite a lot of repos. I guess you would run into rate limit issues quite fast?

Have you tried to increase the request timeout by the env variable GITHUB_EXPORTER_REQUEST_TIMEOUT?

**Comment by tboerger** [comment]
I can't remember the maximum value allowed by the github api, but setting a higher value for GITHUB_EXPORTER_PER_PAGE (defaults to 500) would also be good.

**Comment by dhawalseth** [comment]
Thanks! yeah let me try that as I'm hitting rate limit issues. 


Have you considered using webhooks to get this data instead of APIs like https://github.com/actions/actions-runner-controller/blob/master/docs/monitoring-and-troubleshooting.md#metrics?

**Comment by marcin-motyl** [comment]
I tried couple of webhook based exporters (including ARC), but they all had some issues with reporting correct metrics.

For example, number of started jobs could be less than number of finished jobs.

I suspect the issue is with the GitHub itself and it not reporting all of the events.

So it seems like scrapping approach this project uses is more reliable at the moment.

**Comment by Sundararaju** [comment]
@dhawalseth - did you manage to resolve this issue ? Could you please share the solution if you have got one.

**Comment by Sundararaju** [comment]
Thanks @tboerger. We have increased the timeout and the per page variables as you suggested which has stopped the API rate limit error. However, we have got few other issues for which we will open a new issue.

**Comment by tboerger** [comment]
I have added something to the docs via https://github.com/promhippie/github_exporter/pull/243
