### ISSUE TITLE
Missing explicit check for workflow status failure

### ISSUE THREAD

**Issue by ventsislav-georgiev** [promhippie/github_exporter#230]
The workflow status is documented to have 14 unique values: completed, action_required, cancelled, failure, neutral, skipped, stale, success, timed_out, in_progress, queued, requested, waiting, pending
Ref: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28

From looking at the code: https://github.com/promhippie/github_exporter/blob/d3cef39979ee177a760e764490a2ef56c9cf31c4/pkg/exporter/workflow.go#L273-L304

There is no check if the conclusion is failure and the only way to match against that is to use 0 as a failure status. 
Is this expected?

**Comment by tboerger** [comment]
Yes, 0 should be used for failure. This is something that needs to be properly documented.

**Comment by ventsislav-georgiev** [comment]
Something seems to be wrong with the status reported. I'll have to debug for details but it seems that when the workflow is `In Progress` on Github, getting the metrics from github_exporter reports 0 for `github_workflow_status`. It then changes to 7 when the workflow completes.

**Comment by ventsislav-georgiev** [comment]
@tboerger I've added the following log:
<img width="1282" alt="image" src="https://github.com/promhippie/github_exporter/assets/5616486/46a529d9-ad5c-4943-8ce0-cf4a204339da">

And testing by running a workflow and querying the /metrics endpoint from a local build. Doesn't matter if the Github status is Queued or In Progress, the log is:
```
{"collector":"workflow","conclusion":"","level":"info","msg":"Returned 0 as conclusion","ts":"2023-07-12T16:39:24.072135Z"}
```

It seems the lib used for querying the API returns and empty string in this case...

**Comment by ventsislav-georgiev** [comment]
The label `status` (`record.GetStatus()`) seems to be the one with the expected queued, in_progress and other values. Conclusion returns value after the workflow is finished and it cannot be in most states that are cases in the switch.

**Comment by tboerger** [comment]
Please give it a try with the latest tag of the image, this should work now. After getting it confirmed by you I would tag the new release v2.3.0

**Comment by ventsislav-georgiev** [comment]
@tboerger Thanks! Tried the `latest` tag and it works as expected, scraping `Queued` and `In Progress` states.

**Comment by ventsislav-georgiev** [comment]
@tboerger will you have time to push the v2.3.0 release?

**Comment by tboerger** [comment]
Since nobody complained about it I think I will roll a release after merging https://github.com/promhippie/github_exporter/pull/236 and updating the changelog.

**Comment by tboerger** [comment]
I have just pushed v2.3.0, will be available in a few minutes.
