### ISSUE TITLE
Will not collect similarly named workflows

### ISSUE THREAD

**Issue by jretterer-prol** [promhippie/github_exporter#234]
In my scenario I am trying to collect info about workflows.  We run a lot of copies of the workflows in a short period of time and this seams to trip up the collector resulting in missing info about a lot of the workflows.

I see this in the debug logs (data anonymized):
```
level=debug ts=2023-07-13T17:05:50.187766828Z collector=workflow msg="Fetched workflows" count=70 duration=1.163039389s
...
level=debug ts=2023-07-13T17:05:50.187867274Z collector=workflow msg="Collecting workflow" owner=org/repo name="Product / OS1"
level=debug ts=2023-07-13T17:05:50.187876148Z collector=workflow msg="Collecting workflow" owner=org/repo name="Product / OS2"
level=debug ts=2023-07-13T17:05:50.187886639Z collector=workflow msg="Collecting workflow" owner=org/repo name="Product"
level=debug ts=2023-07-13T17:05:50.187897423Z collector=workflow msg="Collecting workflow" owner=org/repo name="Product / OS3"
level=debug ts=2023-07-13T17:05:50.187906483Z collector=workflow msg="Already collected workflow" owner=org/repo name="Product / OS2"
level=debug ts=2023-07-13T17:05:50.18791209Z collector=workflow msg="Already collected workflow" owner=org/repo name="Product / OS1"
level=debug ts=2023-07-13T17:05:50.187914841Z collector=workflow msg="Already collected workflow" owner=org/repo name="Product"
level=debug ts=2023-07-13T17:05:50.18796688Z collector=workflow msg="Already collected workflow" owner=org/repo name="Product / OS3"
...
```

What looks like is happening is that since it has already collected a workflow with a similar owner and name it skips the rest that are similar.

It looks like this loop may be the culprit?

https://github.com/promhippie/github_exporter/blob/dd9bb94738b5f4fbeea38dac64dfb169a752f7a0/pkg/exporter/workflow.go#L96-L107

**Comment by tboerger** [comment]
This check have been added after people reported issues with prometheus errors like this metric have been already collected.

**Comment by a-a-ron-stone** [comment]
hmmm were experiencing similar behaviour I think...Ours appears to be missing occasional workflow runs. We have a workflow per repo, and these can be run multiple times a day one after each other. I wonder if its doing similar behaviour where it skips a run record because it has the exact same name, only the run number changes?

if thats the case, is there anyway we can make it compare run numbers so we get all the workflow runs?

**Comment by tboerger** [comment]
With all the issues regarding workflow metrics I'm currently thinking about how to reimplement the whole feature.

Currently I'm tending to integrate a webhook listener which got to be configured on repos or orgs as a target, store the state with boltdb or optionally some other database and use the database content to generate the metrics offered by this exporter.

It would be great to gather some feedback by people using this feature at this larger scale as this would turn the exporter into some stateful service.

**Comment by LongChengIn** [comment]
ran into the same issue. it seems to be using `repo name + workflow name` to [dedup](https://github.com/promhippie/github_exporter/blob/f512c6e5bd197c0a2f79e67c61564968e34f231c/pkg/exporter/workflow.go#L97). it always reports the latest run and all previous runs of the same workflow are skipped. 

@tboerger , what do you think about using something like `repo name + workflow name + run_id + retry` as the unique key?

about using GitHub webhooks, if I understand correctly, that would mean GitHub needs to call the exporter. So the exporter has to be exposed on the public Internet. To lots of companies, this may be a security risk. But letting the exporter pull GitHub is ok.

**Comment by tboerger** [comment]
I won't continue the workflow exporter without the webhook integration. The current behavior led to so many issues that have been reported over all mostly related to paging size, timeouts and rate limits. If somebody really thinks that this is such a huge security risk maybe this is just the wrong exporter, sorry.

**Comment by tboerger** [comment]
This current issue should be resolved with https://github.com/promhippie/github_exporter/pull/262 based on webhooks sent from Github.

**Comment by tboerger** [comment]
Hopefully this issue is history with the new webhook-based implementation introduced with https://github.com/promhippie/github_exporter/pull/262, if the issue have not been resolved with the `latest` container image please feel free to report it at https://github.com/promhippie/github_exporter/issues/261 and we will get this fixed ASAP. Be aware that you need to integrate the webhook to receive workflow metrics in the future.
