### ISSUE TITLE
errors in console superfluous response.WriteHeader call and Failed to fetch repo workflows

### ISSUE THREAD

**Issue by a-a-ron-stone** [promhippie/github_exporter#256]
Hi, I've had a read through the issues but cant find anything that seems to match what were experiencing...I'll do my best to explain what were seeing and our setup...

so there are 2 errors that appear in the lofs... one is this...

`exporter-github_exporter-1  | 2023/09/27 07:54:16 http: superfluous response.WriteHeader call from github.com/promhippie/github_exporter/pkg/middleware.Timeout.func1.1 (timeout.go:17)`

and the other is this...

`exporter-github_exporter-1  | {"collector":"workflow","err":"context deadline exceeded","level":"error","msg":"Failed to fetch repo workflows","name":"org_name/*","ts":"2023-09-27T06:54:32.731844299Z"}`

now its worth noting that things appear to be running as expected even with these issues, the scrape happens and can see data on locolhost/metrics and also in prometheus so Im not sure if were getting these against particular repos or what?

We did hit rate limit issues so I think weve managed to control these by manipulating the repos per page and a couple of time out settings. we have approx 1.2K repos we are looking at to pull workflow metrics from. This is our configs

prometheus.yml

 global:
  scrape_interval: 60m
  scrape_timeout: 20m
  evaluation_interval: 1m

scrape_configs:
- job_name: github
  static_configs:
  - targets:
    - github_exporter:9504

docker-compse.yml

version: '2'
global:
version: '2'
version: '2'

volumes:
  prometheus:

services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  github_exporter:
    image: promhippie/github-exporter:latest
    restart: always
    ports:
      - 127.0.0.1:9504:9504
    environment:
      - GITHUB_EXPORTER_TOKEN=TOKEN
      - GITHUB_EXPORTER_ORG=ORG_NAME
      - GITHUB_EXPORTER_REPO=ORG_NAME/*
      - GITHUB_EXPORTER_COLLECTOR_WORKFLOWS=true
      - GITHUB_EXPORTER_REQUEST_TIMEOUT=5m
      - GITHUB_EXPORTER_PER_PAGE=5000
      - GITHUB_EXPORTER_COLLECTOR_REPOS=false
      - GITHUB_EXPORTER_COLLECTOR_ORGS=false
      - GITHUB_EXPORTER_WEB_TIMEOUT=20m

Any help on the 2 errors or guidance on our config would be greatly appreciated

Cheers

**Comment by tboerger** [comment]
workflow metrics I'm currently thinking about how to reimplement the whole feature.

Currently I'm tending to integrate a webhook listener which got to be configured on repos or orgs as a target, store the state with boltdb or optionally some other database and use the database content to generate the metrics offered by this exporter.

It would be great to gather some feedback by people using this feature at this larger scale as this would turn the exporter into some stateful service.

**Comment by tboerger** [comment]
Hopefully this issue is history with the new webhook-based implementation introduced with https://github.com/promhippie/github_exporter/pull/262, if the issue have not been resolved with the `latest` container image please feel free to report it at https://github.com/promhippie/github_exporter/issues/261 and we will get this fixed ASAP. Be aware that you need to integrate the webhook to receive workflow metrics in the future.
