### ISSUE TITLE
Rebuild workflow metrics based on webhooks

### ISSUE THREAD

**Issue by tboerger** [promhippie/github_exporter#261]
To make the workflow metrics integration more reliable and to avoid rate limiting because of the amount of required api calls we should rebuild the workflow metrics based on webhooks sent by GitHub. The webhook will receive all required information by GitHub and will store the information within BoltDB which makes the service sadly a stateful service.

**Comment by tboerger** [comment]
We have introduced this changed behavior for the workflow metrics to avoid running into api rate limit errors which works out pretty well. You are still able to run into api rate limit errors for the other metrics, but you just need to use a proper paging size and do not too often scrape the exporter to avoid that.

I haven't checked the API for deployments, but since those could also be a lot I would suggest to extend the webhook receiver and use this instead.

**Comment by ardole** [comment]
Great, thank you for the feedback !

After check others well known monitoring system for Github are using webhooks as well ;)
