### ISSUE TITLE
Workflow duration is incorrect for reruns

### ISSUE THREAD

**Issue by LongChengIn** [promhippie/github_exporter#267]
Notice that the duration for rerun is incorrect

```
github_workflow_duration_ms{event="workflow_dispatch",head_branch="main",name="name",owner="owner",repo="repo",retry="2",run="1234",run_id="123456",status="completed"} 1.6507e+07
```

It seems that the duration is calculated by [updated_at - created_at](https://github.com/promhippie/github_exporter/blob/f512c6e5bd197c0a2f79e67c61564968e34f231c/pkg/exporter/workflow.go#L142). But for a rerun, the `created_at` is still when the first attempt starts, not when the rerun starts.

from a quick look, using `run_started_at` should fix this

**Comment by tboerger** [comment]
This have been fixed with https://github.com/promhippie/github_exporter/pull/262, thanks for the report.
