### ISSUE TITLE
UNABLE TO FETCH WORKFLOWS

### ISSUE THREAD

**Issue by Adeniji1313** [promhippie/github_exporter#270]
Hi Everyone,

I have not been able to get workflow metrics no matter what I tried. I have been getting this error.  

`level=error ts=2023-10-26T15:34:42.365656874Z msg="failed to store github event" type=workflow_run error="failed to find record: sql: expected 15 destination arguments in Scan, not 1"
2023/10/26 15:34:42 http: superfluous response.WriteHeader call from github.com/promhippie/github_exporter/pkg/action.handler.func2.1 (server.go:289)` 

and then 

`level=error ts=2023-10-26T15:34:50.889038215Z collector=workflow msg="Failed to fetch workflows" err="sql: Scan error on column index 0, name \"owner\": destination not a pointer"`

I use kubernetes

```
  GITHUB_EXPORTER_COLLECTOR_WORKFLOWS: "true"
  GITHUB_EXPORTER_LOG_PRETTY: "true"
  GITHUB_EXPORTER_COLLECTOR_RUNNERS: "true"
  GITHUB_EXPORTER_REQUEST_TIMEOUT: "15m"
  GITHUB_EXPORTER_PER_PAGE: "3000"
```

<img width="1315" alt="Screenshot 2023-10-26 at 17 08 44" src="https://github.com/promhippie/github_exporter/assets/71105480/70569692-b8af-495b-aef1-c781eecc36d9">

**Comment by tboerger** [comment]
Looks like you nare giving `latest` a try which includes a massive change to the behavior of the workflow metrics. Have you setup the webhook as documented?  What exactly have you done? Which configuration have you applied?

**Comment by tboerger** [comment]
I have reproduced the issue locally, a fix is on the way.

Since the new release failed halfway I need to look into excluding SQLite for some os or architectures.

**Comment by tboerger** [comment]
The `latest` tag should be building now, when I'm done with the fixing related to database support I will roll a new release.

**Comment by Adeniji1313** [comment]
Thank you so much. It works now

**Comment by tboerger** [comment]
Sadly no final release yet, still got issues while building everything.

**Comment by tboerger** [comment]
Finally I have released 3.0.1 now! :partying_face:

**Comment by Adeniji1313** [comment]
🥳. I tried it now sir. and the workflow metrics are no more populating 🙁. No error in the logs though

**Comment by tboerger** [comment]
Have you also deleted the database file to start from the scratch?

**Comment by Adeniji1313** [comment]
How do I do that

**Comment by tboerger** [comment]
Depends on how you deployed it. If you have enabled persistence replace the volume, if you haven't make sure the pods are getting deleted to create a new empty dir volume

**Comment by Adeniji1313** [comment]
I am not using a persitent volume. The have recreated the pods numerous times.

**Comment by tboerger** [comment]
You are aware that you got to wait for workflow run events from the GitHub webhook before the metrics are getting displayed, right?
