### ISSUE TITLE
Add custom labels and busy flag to the github runner exporter

### ISSUE THREAD

**Issue by SudeshnaBora** [promhippie/github_exporter#277]
Currently , github runner exporter metrics only give the following properties `"owner", "id", "name", "os", "status"`.
The underlying github client provides additional properties like `labels` and `busy` boolean flag. 
It is helpful to have the labels in case of self hosted runners as those can be used downstream. 
Similarly, having a boolean flag for the `busy` status helps in better incorporation downstream.

**Comment by SudeshnaBora** [comment]
Raised a PR for this same https://github.com/promhippie/github_exporter/pull/276

**Comment by SudeshnaBora** [comment]
Post discussion, merged changes https://github.com/promhippie/github_exporter/pull/283 .

**Comment by tboerger** [comment]
I have released a new version, you can see the changes at https://github.com/promhippie/github_exporter/releases/tag/v3.1.0
