### ISSUE TITLE
Add path to workflow fields

### ISSUE THREAD

**Issue by aleclerc-cio** [promhippie/github_exporter#333]
I'm wondering if we could add `path` to the workflow parameters. 

I found out today that the 'name' field ends up being the display name, which, if you use `run-name` is dynamic, making it impossible (as far as I can tell) to do a group-by on repo/name for each workflow. While `path` it's ideal, it seems to be the only thing in the webhook that is unique enough to reference a workflow if you end up using `run-name` to have a dynamic workflow name.
```
    "path": ".github/workflows/deploy.yaml",
```

**Comment by tboerger** [comment]
I'm open to accept a PR which adds an optional label including the workflow file name.

**Comment by tboerger** [comment]
This should be resolved with the release of v4.0.0, if something is missing or not working please raise an issue. The release should pop up in a few minutes.
