### ISSUE TITLE
Failed to fetch billing

### ISSUE THREAD

**Issue by juris** [promhippie/github_exporter#67]
If I set `GITHUB_EXPORTER_COLLECTOR_ACTIONS=true` billing stats begin to fail with
```
level=error ts=2021-12-15T12:29:00.9668413Z collector=action msg="Failed to fetch billing" type=org name=juroteam err="json: cannot unmarshal number 156.0 into Go struct field actionReponse.total_paid_minutes_used of type int"
```

**Comment by tboerger** [comment]
Sorry for the late response, I had been fulltime off. Strange that it starts to return floats while it had been integegers. Looks like I need to handle another type here.

**Comment by tboerger** [comment]
I will publish a new release including this fix. The PR have already been merged.
