### ISSUE TITLE
Allow wildcard for repos

### ISSUE THREAD

**Issue by tjdavis3** [promhippie/github_exporter#68]
Currently if you want metrics on repos, eg. issues open, you have to list out each repo to query.  It would be nice to be able to either have a flag to show metrics for all repos in an org or use wildcards for the repo names.

**Comment by tboerger** [comment]
What about just enabling the whole organization? I'm not sure how well it works out to enable some globbing.

**Comment by tjdavis3** [comment]
Whole org would work.  I assume it would either need to do make a single GH API call to get all of them at once or periodically pull the API and cache the results for when Prometheus requests the metrics.  The way the queries work causes a timeout if there are too many repos.  In our org we have ~100 repos.  When I created a list of all of them and attempted to scrape it I do not get any results.  If I pare the list down significantly it works.

**Comment by tboerger** [comment]
You allready got the configs for that, give it a try:

```
GITHUB_EXPORTER_ORG, GITHUB_EXPORTER_ORGS
Organizations to scrape metrics from, comma-separated list

GITHUB_EXPORTER_REPO, GITHUB_EXPORTER_REPOS
Repositories to scrape metrics from, comma-separated list
```

**Comment by tjdavis3** [comment]
I tried setting GITHUB_EXPORTER_ORG, but it doesn't pull any repo info.   Manually listing all of the repos had the timeout issue mentioned.  Assuming that worked, it'd be nice to be able to just point it at the org and have it pick up all repos as well as any that got added without needing to reconfigure the exporter.

**Comment by tboerger** [comment]
I will publish a new release including this fix. The PR have already been merged.
