### ISSUE TITLE
New wildcard functionality only works for public repos

### ISSUE THREAD

**Issue by tjdavis3** [promhippie/github_exporter#75]
I finally got around to testing the new wildcard functionality from #68.  It appears that it only works for public repos.  

Two of our private repos are
* circuit_inventory_service
* circuit_inventory_frontend

I tried the following in testing:

GITHUB_EXPORTER_REPO set to my PAT

| Setting | Result |
| --- | --- |
GITHUB_EXPORTER_REPO={org}/* | Only public repos appear |
GITHUB_EXPORTER_REPO=(org}/circuit* | No repos appear |
GITHUB_EXPORTER_REPO={org}/circuit_inventory_service | circuit_inventory_service repo appears |

**Comment by tboerger** [comment]
I have merged https://github.com/promhippie/github_exporter/pull/76, please test the `latest` Docker tag, if everything works I will tag v1.1.1 which should resolve the issue.

**Comment by tjdavis3** [comment]
Confirmed private repos work via wildcard in latest Docker tag.

**Comment by tboerger** [comment]
Great, than I can publish a Bugfix release
