### ISSUE TITLE
Github Token permissions scope

### ISSUE THREAD

**Issue by nvtkaszpir** [promhippie/github_exporter#95]
Hi, please provide minimum github token scope permissions to make app running in read-only mode.
Thanks in advance.

**Comment by tboerger** [comment]
I think the read repos permission should be enough, but I need to verify that.

**Comment by tboerger** [comment]
FYI just releasing a new version which supports GitHub apps instead of some static token.

**Comment by norman-zon** [comment]
Could you add documentation on which permissions the Github app needs?

**Comment by tboerger** [comment]
Yeah, I need to get back to that and click me through all the possible options.
